/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedSummaryOfGradesRouteImport } from './routes/_authenticated/summary-of-grades'
import { Route as AuthenticatedSubjectTeacherDashboardRouteImport } from './routes/_authenticated/subject-teacher-dashboard'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSogReportRouteImport } from './routes/_authenticated/sog-report'
import { Route as AuthenticatedSf9MatatagRouteImport } from './routes/_authenticated/sf9-matatag'
import { Route as AuthenticatedSf8RouteImport } from './routes/_authenticated/sf8'
import { Route as AuthenticatedSf6RouteImport } from './routes/_authenticated/sf6'
import { Route as AuthenticatedSf5RouteImport } from './routes/_authenticated/sf5'
import { Route as AuthenticatedSf10RouteImport } from './routes/_authenticated/sf10'
import { Route as AuthenticatedSf1RouteImport } from './routes/_authenticated/sf1'
import { Route as AuthenticatedSchoolInfoRouteImport } from './routes/_authenticated/school-info'
import { Route as AuthenticatedSchoolFormsRouteImport } from './routes/_authenticated/school-forms'
import { Route as AuthenticatedRequestFormRouteImport } from './routes/_authenticated/request-form'
import { Route as AuthenticatedReceivedRequestsRouteImport } from './routes/_authenticated/received-requests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedGsaRouteImport } from './routes/_authenticated/gsa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCredentialRequestsRouteImport } from './routes/_authenticated/credential-requests'
import { Route as AuthenticatedAnecdotalRecordRouteImport } from './routes/_authenticated/anecdotal-record'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes.$classId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummaryOfGradesRoute =
  AuthenticatedSummaryOfGradesRouteImport.update({
    id: '/summary-of-grades',
    path: '/summary-of-grades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectTeacherDashboardRoute =
  AuthenticatedSubjectTeacherDashboardRouteImport.update({
    id: '/subject-teacher-dashboard',
    path: '/subject-teacher-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSogReportRoute = AuthenticatedSogReportRouteImport.update({
  id: '/sog-report',
  path: '/sog-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf9MatatagRoute = AuthenticatedSf9MatatagRouteImport.update({
  id: '/sf9-matatag',
  path: '/sf9-matatag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf8Route = AuthenticatedSf8RouteImport.update({
  id: '/sf8',
  path: '/sf8',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf6Route = AuthenticatedSf6RouteImport.update({
  id: '/sf6',
  path: '/sf6',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf5Route = AuthenticatedSf5RouteImport.update({
  id: '/sf5',
  path: '/sf5',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf10Route = AuthenticatedSf10RouteImport.update({
  id: '/sf10',
  path: '/sf10',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSf1Route = AuthenticatedSf1RouteImport.update({
  id: '/sf1',
  path: '/sf1',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolInfoRoute = AuthenticatedSchoolInfoRouteImport.update({
  id: '/school-info',
  path: '/school-info',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolFormsRoute =
  AuthenticatedSchoolFormsRouteImport.update({
    id: '/school-forms',
    path: '/school-forms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestFormRoute =
  AuthenticatedRequestFormRouteImport.update({
    id: '/request-form',
    path: '/request-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceivedRequestsRoute =
  AuthenticatedReceivedRequestsRouteImport.update({
    id: '/received-requests',
    path: '/received-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGsaRoute = AuthenticatedGsaRouteImport.update({
  id: '/gsa',
  path: '/gsa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredentialRequestsRoute =
  AuthenticatedCredentialRequestsRouteImport.update({
    id: '/credential-requests',
    path: '/credential-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnecdotalRecordRoute =
  AuthenticatedAnecdotalRecordRouteImport.update({
    id: '/anecdotal-record',
    path: '/anecdotal-record',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/anecdotal-record': typeof AuthenticatedAnecdotalRecordRoute
  '/credential-requests': typeof AuthenticatedCredentialRequestsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gsa': typeof AuthenticatedGsaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/received-requests': typeof AuthenticatedReceivedRequestsRoute
  '/request-form': typeof AuthenticatedRequestFormRoute
  '/school-forms': typeof AuthenticatedSchoolFormsRoute
  '/school-info': typeof AuthenticatedSchoolInfoRoute
  '/sf1': typeof AuthenticatedSf1Route
  '/sf10': typeof AuthenticatedSf10Route
  '/sf5': typeof AuthenticatedSf5Route
  '/sf6': typeof AuthenticatedSf6Route
  '/sf8': typeof AuthenticatedSf8Route
  '/sf9-matatag': typeof AuthenticatedSf9MatatagRoute
  '/sog-report': typeof AuthenticatedSogReportRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subject-teacher-dashboard': typeof AuthenticatedSubjectTeacherDashboardRoute
  '/summary-of-grades': typeof AuthenticatedSummaryOfGradesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/anecdotal-record': typeof AuthenticatedAnecdotalRecordRoute
  '/credential-requests': typeof AuthenticatedCredentialRequestsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gsa': typeof AuthenticatedGsaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/received-requests': typeof AuthenticatedReceivedRequestsRoute
  '/request-form': typeof AuthenticatedRequestFormRoute
  '/school-forms': typeof AuthenticatedSchoolFormsRoute
  '/school-info': typeof AuthenticatedSchoolInfoRoute
  '/sf1': typeof AuthenticatedSf1Route
  '/sf10': typeof AuthenticatedSf10Route
  '/sf5': typeof AuthenticatedSf5Route
  '/sf6': typeof AuthenticatedSf6Route
  '/sf8': typeof AuthenticatedSf8Route
  '/sf9-matatag': typeof AuthenticatedSf9MatatagRoute
  '/sog-report': typeof AuthenticatedSogReportRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subject-teacher-dashboard': typeof AuthenticatedSubjectTeacherDashboardRoute
  '/summary-of-grades': typeof AuthenticatedSummaryOfGradesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/anecdotal-record': typeof AuthenticatedAnecdotalRecordRoute
  '/_authenticated/credential-requests': typeof AuthenticatedCredentialRequestsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gsa': typeof AuthenticatedGsaRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/received-requests': typeof AuthenticatedReceivedRequestsRoute
  '/_authenticated/request-form': typeof AuthenticatedRequestFormRoute
  '/_authenticated/school-forms': typeof AuthenticatedSchoolFormsRoute
  '/_authenticated/school-info': typeof AuthenticatedSchoolInfoRoute
  '/_authenticated/sf1': typeof AuthenticatedSf1Route
  '/_authenticated/sf10': typeof AuthenticatedSf10Route
  '/_authenticated/sf5': typeof AuthenticatedSf5Route
  '/_authenticated/sf6': typeof AuthenticatedSf6Route
  '/_authenticated/sf8': typeof AuthenticatedSf8Route
  '/_authenticated/sf9-matatag': typeof AuthenticatedSf9MatatagRoute
  '/_authenticated/sog-report': typeof AuthenticatedSogReportRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/subject-teacher-dashboard': typeof AuthenticatedSubjectTeacherDashboardRoute
  '/_authenticated/summary-of-grades': typeof AuthenticatedSummaryOfGradesRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/anecdotal-record'
    | '/credential-requests'
    | '/dashboard'
    | '/gsa'
    | '/notifications'
    | '/profile'
    | '/received-requests'
    | '/request-form'
    | '/school-forms'
    | '/school-info'
    | '/sf1'
    | '/sf10'
    | '/sf5'
    | '/sf6'
    | '/sf8'
    | '/sf9-matatag'
    | '/sog-report'
    | '/students'
    | '/subject-teacher-dashboard'
    | '/summary-of-grades'
    | '/transfers'
    | '/classes/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/anecdotal-record'
    | '/credential-requests'
    | '/dashboard'
    | '/gsa'
    | '/notifications'
    | '/profile'
    | '/received-requests'
    | '/request-form'
    | '/school-forms'
    | '/school-info'
    | '/sf1'
    | '/sf10'
    | '/sf5'
    | '/sf6'
    | '/sf8'
    | '/sf9-matatag'
    | '/sog-report'
    | '/students'
    | '/subject-teacher-dashboard'
    | '/summary-of-grades'
    | '/transfers'
    | '/classes/$classId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/anecdotal-record'
    | '/_authenticated/credential-requests'
    | '/_authenticated/dashboard'
    | '/_authenticated/gsa'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/received-requests'
    | '/_authenticated/request-form'
    | '/_authenticated/school-forms'
    | '/_authenticated/school-info'
    | '/_authenticated/sf1'
    | '/_authenticated/sf10'
    | '/_authenticated/sf5'
    | '/_authenticated/sf6'
    | '/_authenticated/sf8'
    | '/_authenticated/sf9-matatag'
    | '/_authenticated/sog-report'
    | '/_authenticated/students'
    | '/_authenticated/subject-teacher-dashboard'
    | '/_authenticated/summary-of-grades'
    | '/_authenticated/transfers'
    | '/_authenticated/classes/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary-of-grades': {
      id: '/_authenticated/summary-of-grades'
      path: '/summary-of-grades'
      fullPath: '/summary-of-grades'
      preLoaderRoute: typeof AuthenticatedSummaryOfGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-teacher-dashboard': {
      id: '/_authenticated/subject-teacher-dashboard'
      path: '/subject-teacher-dashboard'
      fullPath: '/subject-teacher-dashboard'
      preLoaderRoute: typeof AuthenticatedSubjectTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sog-report': {
      id: '/_authenticated/sog-report'
      path: '/sog-report'
      fullPath: '/sog-report'
      preLoaderRoute: typeof AuthenticatedSogReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf9-matatag': {
      id: '/_authenticated/sf9-matatag'
      path: '/sf9-matatag'
      fullPath: '/sf9-matatag'
      preLoaderRoute: typeof AuthenticatedSf9MatatagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf8': {
      id: '/_authenticated/sf8'
      path: '/sf8'
      fullPath: '/sf8'
      preLoaderRoute: typeof AuthenticatedSf8RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf6': {
      id: '/_authenticated/sf6'
      path: '/sf6'
      fullPath: '/sf6'
      preLoaderRoute: typeof AuthenticatedSf6RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf5': {
      id: '/_authenticated/sf5'
      path: '/sf5'
      fullPath: '/sf5'
      preLoaderRoute: typeof AuthenticatedSf5RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf10': {
      id: '/_authenticated/sf10'
      path: '/sf10'
      fullPath: '/sf10'
      preLoaderRoute: typeof AuthenticatedSf10RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sf1': {
      id: '/_authenticated/sf1'
      path: '/sf1'
      fullPath: '/sf1'
      preLoaderRoute: typeof AuthenticatedSf1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-info': {
      id: '/_authenticated/school-info'
      path: '/school-info'
      fullPath: '/school-info'
      preLoaderRoute: typeof AuthenticatedSchoolInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-forms': {
      id: '/_authenticated/school-forms'
      path: '/school-forms'
      fullPath: '/school-forms'
      preLoaderRoute: typeof AuthenticatedSchoolFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request-form': {
      id: '/_authenticated/request-form'
      path: '/request-form'
      fullPath: '/request-form'
      preLoaderRoute: typeof AuthenticatedRequestFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/received-requests': {
      id: '/_authenticated/received-requests'
      path: '/received-requests'
      fullPath: '/received-requests'
      preLoaderRoute: typeof AuthenticatedReceivedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gsa': {
      id: '/_authenticated/gsa'
      path: '/gsa'
      fullPath: '/gsa'
      preLoaderRoute: typeof AuthenticatedGsaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credential-requests': {
      id: '/_authenticated/credential-requests'
      path: '/credential-requests'
      fullPath: '/credential-requests'
      preLoaderRoute: typeof AuthenticatedCredentialRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anecdotal-record': {
      id: '/_authenticated/anecdotal-record'
      path: '/anecdotal-record'
      fullPath: '/anecdotal-record'
      preLoaderRoute: typeof AuthenticatedAnecdotalRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnecdotalRecordRoute: typeof AuthenticatedAnecdotalRecordRoute
  AuthenticatedCredentialRequestsRoute: typeof AuthenticatedCredentialRequestsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGsaRoute: typeof AuthenticatedGsaRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReceivedRequestsRoute: typeof AuthenticatedReceivedRequestsRoute
  AuthenticatedRequestFormRoute: typeof AuthenticatedRequestFormRoute
  AuthenticatedSchoolFormsRoute: typeof AuthenticatedSchoolFormsRoute
  AuthenticatedSchoolInfoRoute: typeof AuthenticatedSchoolInfoRoute
  AuthenticatedSf1Route: typeof AuthenticatedSf1Route
  AuthenticatedSf10Route: typeof AuthenticatedSf10Route
  AuthenticatedSf5Route: typeof AuthenticatedSf5Route
  AuthenticatedSf6Route: typeof AuthenticatedSf6Route
  AuthenticatedSf8Route: typeof AuthenticatedSf8Route
  AuthenticatedSf9MatatagRoute: typeof AuthenticatedSf9MatatagRoute
  AuthenticatedSogReportRoute: typeof AuthenticatedSogReportRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedSubjectTeacherDashboardRoute: typeof AuthenticatedSubjectTeacherDashboardRoute
  AuthenticatedSummaryOfGradesRoute: typeof AuthenticatedSummaryOfGradesRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnecdotalRecordRoute: AuthenticatedAnecdotalRecordRoute,
  AuthenticatedCredentialRequestsRoute: AuthenticatedCredentialRequestsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGsaRoute: AuthenticatedGsaRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReceivedRequestsRoute: AuthenticatedReceivedRequestsRoute,
  AuthenticatedRequestFormRoute: AuthenticatedRequestFormRoute,
  AuthenticatedSchoolFormsRoute: AuthenticatedSchoolFormsRoute,
  AuthenticatedSchoolInfoRoute: AuthenticatedSchoolInfoRoute,
  AuthenticatedSf1Route: AuthenticatedSf1Route,
  AuthenticatedSf10Route: AuthenticatedSf10Route,
  AuthenticatedSf5Route: AuthenticatedSf5Route,
  AuthenticatedSf6Route: AuthenticatedSf6Route,
  AuthenticatedSf8Route: AuthenticatedSf8Route,
  AuthenticatedSf9MatatagRoute: AuthenticatedSf9MatatagRoute,
  AuthenticatedSogReportRoute: AuthenticatedSogReportRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedSubjectTeacherDashboardRoute:
    AuthenticatedSubjectTeacherDashboardRoute,
  AuthenticatedSummaryOfGradesRoute: AuthenticatedSummaryOfGradesRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
