-- ============================================================
-- Admin School Year Control + School Year Library
-- ============================================================
-- This migration combines:
--   1. The original active/locked School Year setting
--   2. The new Admin School Year Library
--   3. Teacher-side validation on public.classes
--
-- Behavior:
-- - Admin can add many School Years to the library.
-- - Only one School Year can be locked/active at a time.
-- - Locking a library year synchronizes public.school_year_settings.
-- - Unlocking removes the active lock but keeps the year for history.
-- - Unlocked library years can be deleted without deleting classes/grades.
-- - If the Admin locks one School Year, teachers can use only that locked year.
-- - If the Admin unlocks all School Years, teachers cannot create a new
--   class or change a class School Year until the Admin locks one again.
-- - Existing historical classes remain editable when their School Year is
--   not being changed.
-- ============================================================

begin;

-- ============================================================
-- 1. ACTIVE SCHOOL YEAR SINGLETON
-- ============================================================

create table if not exists public.school_year_settings (
  id smallint primary key default 1 check (id = 1),
  school_year text,
  is_locked boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint school_year_settings_format_check check (
    school_year is null
    or school_year ~ '^[0-9]{4}-[0-9]{4}$'
  )
);

insert into public.school_year_settings (
  id,
  school_year,
  is_locked
)
values (
  1,
  null,
  false
)
on conflict (id) do nothing;

alter table public.school_year_settings enable row level security;

drop policy if exists "authenticated read school year setting"
  on public.school_year_settings;

create policy "authenticated read school year setting"
on public.school_year_settings
for select
to authenticated
using (true);

drop policy if exists "admins insert school year setting"
  on public.school_year_settings;

create policy "admins insert school year setting"
on public.school_year_settings
for insert
to authenticated
with check (public.is_admin(auth.uid()));

drop policy if exists "admins update school year setting"
  on public.school_year_settings;

create policy "admins update school year setting"
on public.school_year_settings
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

grant select, insert, update
on public.school_year_settings
to authenticated;


-- ============================================================
-- 2. SCHOOL YEAR LIBRARY
-- ============================================================

create table if not exists public.school_year_library (
  id bigint generated by default as identity primary key,
  school_year text not null unique,
  is_locked boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_year_library_format_check check (
    school_year ~ '^[0-9]{4}-[0-9]{4}$'
  )
);

alter table public.school_year_library enable row level security;

drop policy if exists "authenticated read school year library"
  on public.school_year_library;

create policy "authenticated read school year library"
on public.school_year_library
for select
to authenticated
using (true);

-- Teachers need SELECT access.
-- The current Admin UI also writes directly to this table, so Admin-only
-- INSERT / UPDATE / DELETE policies are provided in addition to the RPCs.

drop policy if exists "admins insert school year library"
  on public.school_year_library;

create policy "admins insert school year library"
on public.school_year_library
for insert
to authenticated
with check (public.is_admin(auth.uid()));

drop policy if exists "admins update school year library"
  on public.school_year_library;

create policy "admins update school year library"
on public.school_year_library
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "admins delete school year library"
  on public.school_year_library;

create policy "admins delete school year library"
on public.school_year_library
for delete
to authenticated
using (public.is_admin(auth.uid()));

grant select, insert, update, delete
on public.school_year_library
to authenticated;

-- Identity column support for direct Admin INSERTs.
grant usage, select
on sequence public.school_year_library_id_seq
to authenticated;


-- ============================================================
-- 3. SEED / SYNCHRONIZE THE LIBRARY
-- ============================================================

-- Preserve all historical School Years already present in classes.
insert into public.school_year_library (
  school_year,
  is_locked
)
select distinct
  btrim(c.school_year),
  false
from public.classes c
where c.school_year ~ '^[0-9]{4}-[0-9]{4}$'
on conflict (school_year) do nothing;

-- Preserve the current singleton School Year in the library, if one exists.
insert into public.school_year_library (
  school_year,
  is_locked,
  created_by,
  updated_at
)
select
  btrim(s.school_year),
  false,
  s.updated_by,
  s.updated_at
from public.school_year_settings s
where s.id = 1
  and nullif(btrim(s.school_year), '') is not null
on conflict (school_year) do update
set
  updated_at = greatest(
    public.school_year_library.updated_at,
    excluded.updated_at
  );

-- Make the library lock state exactly match the singleton active setting.
-- This also makes this migration safe to rerun if a previous library version
-- already exists.
update public.school_year_library
set
  is_locked = false,
  updated_at = now()
where is_locked = true;

update public.school_year_library l
set
  is_locked = true,
  updated_at = now()
from public.school_year_settings s
where s.id = 1
  and s.is_locked = true
  and nullif(btrim(s.school_year), '') is not null
  and l.school_year = btrim(s.school_year);

-- Only one library School Year may be active/locked at a time.
create unique index if not exists school_year_library_one_locked_idx
  on public.school_year_library ((1))
  where is_locked = true;


-- ============================================================
-- 4. ADMIN: ADD SCHOOL YEAR
-- ============================================================

create or replace function public.admin_add_school_year(
  p_school_year text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_school_year text;
  v_start_year integer;
  v_end_year integer;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Administrator access is required.';
  end if;

  v_school_year := regexp_replace(
    replace(
      replace(
        btrim(coalesce(p_school_year, '')),
        '–',
        '-'
      ),
      '—',
      '-'
    ),
    '\s+',
    '',
    'g'
  );

  if v_school_year !~ '^[0-9]{4}-[0-9]{4}$' then
    raise exception 'Use a valid School Year such as 2026-2027.';
  end if;

  v_start_year := split_part(v_school_year, '-', 1)::integer;
  v_end_year := split_part(v_school_year, '-', 2)::integer;

  if v_end_year <> v_start_year + 1 then
    raise exception
      'The ending year must be exactly one year after the starting year.';
  end if;

  insert into public.school_year_library (
    school_year,
    is_locked,
    created_by,
    updated_at
  )
  values (
    v_school_year,
    false,
    auth.uid(),
    now()
  )
  on conflict (school_year) do nothing;
end;
$$;


-- ============================================================
-- 5. ADMIN: LOCK / UNLOCK SCHOOL YEAR
-- ============================================================

create or replace function public.admin_set_school_year_lock(
  p_library_id bigint,
  p_locked boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_school_year text;
  v_start_year integer;
  v_end_year integer;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Administrator access is required.';
  end if;

  select school_year
  into v_school_year
  from public.school_year_library
  where id = p_library_id;

  if v_school_year is null then
    raise exception 'School Year was not found.';
  end if;

  -- Extra validation before a year can become active.
  if v_school_year !~ '^[0-9]{4}-[0-9]{4}$' then
    raise exception 'Use a valid School Year such as 2026-2027.';
  end if;

  v_start_year := split_part(v_school_year, '-', 1)::integer;
  v_end_year := split_part(v_school_year, '-', 2)::integer;

  if v_end_year <> v_start_year + 1 then
    raise exception
      'The ending year must be exactly one year after the starting year.';
  end if;

  if coalesce(p_locked, false) then
    -- Unlock any previous active year first.
    update public.school_year_library
    set
      is_locked = false,
      updated_at = now()
    where is_locked = true
      and id <> p_library_id;

    -- Lock the selected library year.
    update public.school_year_library
    set
      is_locked = true,
      updated_at = now()
    where id = p_library_id;

    -- Synchronize the original singleton used by Class Adviser,
    -- Subject Teacher, and class validation.
    insert into public.school_year_settings (
      id,
      school_year,
      is_locked,
      updated_by,
      updated_at
    )
    values (
      1,
      v_school_year,
      true,
      auth.uid(),
      now()
    )
    on conflict (id) do update
    set
      school_year = excluded.school_year,
      is_locked = true,
      updated_by = excluded.updated_by,
      updated_at = excluded.updated_at;

  else
    -- Unlock the selected library year.
    update public.school_year_library
    set
      is_locked = false,
      updated_at = now()
    where id = p_library_id;

    -- Remove the active singleton lock. The School Year remains in the
    -- library for history, but there is no active School Year until one is
    -- locked again by the Administrator.
    update public.school_year_settings
    set
      school_year = null,
      is_locked = false,
      updated_by = auth.uid(),
      updated_at = now()
    where id = 1
      and school_year = v_school_year;
  end if;
end;
$$;


-- ============================================================
-- 6. ADMIN: DELETE SCHOOL YEAR FROM LIBRARY
-- ============================================================

create or replace function public.admin_delete_school_year(
  p_library_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_school_year text;
  v_is_locked boolean;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Administrator access is required.';
  end if;

  select
    school_year,
    is_locked
  into
    v_school_year,
    v_is_locked
  from public.school_year_library
  where id = p_library_id;

  if v_school_year is null then
    return;
  end if;

  if coalesce(v_is_locked, false) then
    raise exception
      'Unlock % before deleting it from the School Year library.',
      v_school_year;
  end if;

  -- This removes only the School Year library entry.
  -- Existing classes, grades, and historical records are not deleted.
  delete from public.school_year_library
  where id = p_library_id;

  -- If the unlocked year was still stored in the singleton, clear that
  -- inactive/stale value. This does not change any historical class record.
  update public.school_year_settings
  set
    school_year = null,
    is_locked = false,
    updated_by = auth.uid(),
    updated_at = now()
  where id = 1
    and is_locked = false
    and school_year = v_school_year;
end;
$$;


-- ============================================================
-- 7. RPC PERMISSIONS
-- ============================================================

-- SECURITY DEFINER functions should not be executable by anonymous/public
-- callers. The functions also perform an Admin check internally.
revoke all on function public.admin_add_school_year(text) from public;
revoke all on function public.admin_set_school_year_lock(bigint, boolean) from public;
revoke all on function public.admin_delete_school_year(bigint) from public;

grant execute
on function public.admin_add_school_year(text)
to authenticated;

grant execute
on function public.admin_set_school_year_lock(bigint, boolean)
to authenticated;

grant execute
on function public.admin_delete_school_year(bigint)
to authenticated;


-- ============================================================
-- 8. ENFORCE SCHOOL YEAR RULES ON CLASSES
-- ============================================================
-- Rules:
--   A. Admin has a LOCKED School Year:
--      - only that exact School Year may be inserted/changed.
--
--   B. Admin has NO locked School Year:
--      - a new class cannot be created,
--      - a class School Year cannot be changed,
--      - the Administrator must lock one School Year first.
--
--   C. Existing historical classes:
--      - remain editable when school_year itself is not being changed.
-- ============================================================

create or replace function public.validate_locked_school_year()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_active_school_year text;
  v_is_locked boolean;
  v_requested_school_year text;
  v_start_year integer;
  v_end_year integer;
begin
  -- Existing historical classes remain editable when the School Year
  -- itself is not being changed.
  if tg_op = 'UPDATE'
     and new.school_year is not distinct from old.school_year then
    return new;
  end if;

  -- Service/background operations without an authenticated user are not
  -- blocked by this teacher-facing rule.
  if auth.uid() is null then
    return new;
  end if;

  -- Normalize the requested class School Year.
  v_requested_school_year := nullif(btrim(new.school_year), '');

  if v_requested_school_year is null then
    raise exception
      'Select a School Year from the Administrator''s School Year Library.';
  end if;

  -- Always validate the School Year format.
  if v_requested_school_year !~ '^[0-9]{4}-[0-9]{4}$' then
    raise exception
      'Use a valid School Year such as 2026-2027.';
  end if;

  v_start_year := split_part(v_requested_school_year, '-', 1)::integer;
  v_end_year := split_part(v_requested_school_year, '-', 2)::integer;

  if v_end_year <> v_start_year + 1 then
    raise exception
      'The ending year must be exactly one year after the starting year.';
  end if;

  -- Read the Admin's current active/locked setting.
  select
    school_year,
    is_locked
  into
    v_active_school_year,
    v_is_locked
  from public.school_year_settings
  where id = 1;

  -- ------------------------------------------------------------
  -- CASE A: Admin has locked a School Year.
  -- Only the locked year is allowed.
  -- ------------------------------------------------------------
  if coalesce(v_is_locked, false)
     and nullif(btrim(v_active_school_year), '') is not null then

    if v_requested_school_year <> btrim(v_active_school_year) then
      raise exception
        'Only the active School Year % is allowed.',
        v_active_school_year;
    end if;

    new.school_year := btrim(v_active_school_year);
    return new;
  end if;

  -- ------------------------------------------------------------
  -- CASE B: Nothing is locked.
  -- Do not allow a new class or a School Year change.
  -- ------------------------------------------------------------
  raise exception
    'No School Year is currently locked. Ask the Administrator to lock a School Year before creating a class.';
end;
$$;

drop trigger if exists enforce_locked_school_year_on_classes
  on public.classes;

create trigger enforce_locked_school_year_on_classes
before insert or update of school_year
on public.classes
for each row
execute function public.validate_locked_school_year();



-- ============================================================
-- 9. FINAL LOCK CONSISTENCY CHECK
-- ============================================================
-- The singleton is the source of truth for the currently active School Year.
-- Clear any stale library locks, then restore only the singleton's matching
-- library row when the singleton is locked.

update public.school_year_library
set
  is_locked = false,
  updated_at = now()
where is_locked = true;

update public.school_year_library l
set
  is_locked = true,
  updated_at = now()
from public.school_year_settings s
where s.id = 1
  and s.is_locked = true
  and nullif(btrim(s.school_year), '') is not null
  and l.school_year = btrim(s.school_year);

commit;

notify pgrst, 'reload schema';
