-- SIGLA: COMPLETE Admin Analytics & Insights -> Delete Class migration.
--
-- IMPORTANT: In the Supabase SQL Editor, open a NEW QUERY, paste this ENTIRE
-- file starting with BEGIN; and ending with the verification SELECT, and
-- press RUN. Running only a fragment beginning with "FROM public.classes"
-- causes ERROR 42601 because FROM must belong to a preceding PERFORM/SELECT.
--
-- Requires the existing public.is_admin(uuid) function and the existing
-- project tables. Do not use this as a replacement for the base schema.
-- This file creates/updates the deletion RPC; it DOES NOT delete a class
-- when installed. Actual deletion only occurs if the authenticated Admin
-- later clicks Delete Class in the app (or invokes the RPC).
--
-- WARNING: Invoking the RPC permanently deletes the selected class and
-- class-linked records, including relevant grade-request/transfer history.
-- Back up the database and test with an expendable class first.

begin;

create or replace function public.admin_delete_analytics_class(p_class_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_caller_id uuid := auth.uid();
  v_deleted_count integer := 0;
begin
  -- Only a logged-in Admin may delete a class.
  if v_caller_id is null or not public.is_admin(v_caller_id) then
    raise exception 'Only an administrator can delete a class.'
      using errcode = '42501';
  end if;

  if p_class_id is null then
    raise exception 'Select a class to delete.';
  end if;

  -- Lock the particular class so concurrent deletion cannot race.
  -- Keep this PERFORM together with its FROM clause.
  perform 1
    from public.classes as selected_class
   where selected_class.id = p_class_id
   for update;

  if not found then
    return false; -- The class has already been removed.
  end if;

  -- First remove grade-request subjects while their parent batch remains.
  -- Then remove any status history generated by the child-delete triggers.
  -- Finally remove the selected class's batches.
  if pg_catalog.to_regclass('public.grade_request_batches') is not null then
    perform 1
      from public.grade_request_batches as batch
     where batch.advisory_class_id = p_class_id
     for update;

    if pg_catalog.to_regclass('public.grade_request_subjects') is not null then
      delete from public.grade_request_subjects as request_subject
       where request_subject.batch_id in (
         select batch.id
           from public.grade_request_batches as batch
          where batch.advisory_class_id = p_class_id
       );
    end if;

    if pg_catalog.to_regclass('public.grade_request_history') is not null then
      delete from public.grade_request_history as history
       where history.batch_id in (
         select batch.id
           from public.grade_request_batches as batch
          where batch.advisory_class_id = p_class_id
       );
    end if;

    delete from public.grade_request_batches as batch
     where batch.advisory_class_id = p_class_id;
  end if;

  -- Earlier installs may have a RESTRICT FK from transfer history to
  -- students. Remove only transfers belonging to learners in THIS class.
  if pg_catalog.to_regclass('public.student_transfers') is not null then
    execute '
      delete from public.student_transfers as transfer
       where transfer.student_id in (
         select student.id
           from public.students as student
          where student.class_id = $1
       )
    ' using p_class_id;
  end if;

  -- Other dependent records follow the existing database FK rules.
  delete from public.classes as selected_class
   where selected_class.id = p_class_id;

  get diagnostics v_deleted_count = row_count;
  return v_deleted_count = 1;
end;
$function$;

-- The Admin check is performed inside the SECURITY DEFINER RPC.
revoke all on function public.admin_delete_analytics_class(uuid)
  from public, anon, authenticated;
grant execute on function public.admin_delete_analytics_class(uuid)
  to authenticated;

commit;

notify pgrst, 'reload schema';

-- Verification only: should return TRUE; does not delete any class.
select pg_catalog.to_regprocedure('public.admin_delete_analytics_class(uuid)') is not null
  as admin_class_delete_installed;
